"""init database

Revision ID: f82edef962c3
Revises: 
Create Date: 2025-12-12 16:32:58.062891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f82edef962c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_details',
    sa.Column('tax_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tax_name', sa.String(length=100), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='check_tax_rate'),
    sa.PrimaryKeyConstraint('tax_id')
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tax_id'], ['tax_details.tax_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_store_id', 'users', ['store_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expense_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='expenses_amount_check'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index('idx_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('idx_expenses_store_id', 'expenses', ['store_id'], unique=False)
    op.create_index('idx_expenses_user_id', 'expenses', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.category_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    op.create_index('idx_products_sku', 'products', ['sku'], unique=False)
    op.create_index('idx_products_store_id', 'products', ['store_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='transactions_total_amount_check'),
    sa.CheckConstraint('total_tax >= 0', name='transactions_total_tax_check'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('idx_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_transactions_store_id', 'transactions', ['store_id'], unique=False)
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_table('batches',
    sa.Column('batch_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('import_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expire_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('cost >= 0', name='batches_cost_check'),
    sa.CheckConstraint('sale_price >= 0', name='batches_sale_price_check'),
    sa.CheckConstraint('stock >= 0', name='batches_stock_check'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('idx_batches_expire_date', 'batches', ['expire_date'], unique=False)
    op.create_index('idx_batches_product_id', 'batches', ['product_id'], unique=False)
    op.create_index('idx_batches_stock', 'batches', ['stock'], unique=False, postgresql_where=sa.text('stock > 0'))
    op.create_index('idx_batches_warehouse_id', 'batches', ['warehouse_id'], unique=False)
    op.create_table('general_ledger_entries',
    sa.Column('entry_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('account_type', postgresql.ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='account_type'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (debit_amount = 0 AND credit_amount > 0)', name='check_debit_or_credit'),
    sa.CheckConstraint('credit_amount >= 0', name='ledger_credit_check'),
    sa.CheckConstraint('debit_amount >= 0', name='ledger_debit_check'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.expense_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index('idx_ledger_account_type', 'general_ledger_entries', ['account_type'], unique=False)
    op.create_index('idx_ledger_entry_date', 'general_ledger_entries', ['entry_date'], unique=False)
    op.create_index('idx_ledger_expense_id', 'general_ledger_entries', ['expense_id'], unique=False)
    op.create_index('idx_ledger_store_id', 'general_ledger_entries', ['store_id'], unique=False)
    op.create_index('idx_ledger_transaction_id', 'general_ledger_entries', ['transaction_id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_sale', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cost_at_sale', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('cost_at_sale >= 0', name='transaction_items_cost_check'),
    sa.CheckConstraint('price_at_sale >= 0', name='transaction_items_price_check'),
    sa.CheckConstraint('quantity > 0', name='transaction_items_quantity_check'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_transaction_items_batch_id', 'transaction_items', ['batch_id'], unique=False)
    op.create_index('idx_transaction_items_transaction_id', 'transaction_items', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_items_transaction_id', table_name='transaction_items')
    op.drop_index('idx_transaction_items_batch_id', table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index('idx_ledger_transaction_id', table_name='general_ledger_entries')
    op.drop_index('idx_ledger_store_id', table_name='general_ledger_entries')
    op.drop_index('idx_ledger_expense_id', table_name='general_ledger_entries')
    op.drop_index('idx_ledger_entry_date', table_name='general_ledger_entries')
    op.drop_index('idx_ledger_account_type', table_name='general_ledger_entries')
    op.drop_table('general_ledger_entries')
    op.drop_index('idx_batches_warehouse_id', table_name='batches')
    op.drop_index('idx_batches_stock', table_name='batches', postgresql_where=sa.text('stock > 0'))
    op.drop_index('idx_batches_product_id', table_name='batches')
    op.drop_index('idx_batches_expire_date', table_name='batches')
    op.drop_table('batches')
    op.drop_index('idx_transactions_user_id', table_name='transactions')
    op.drop_index('idx_transactions_store_id', table_name='transactions')
    op.drop_index('idx_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_products_store_id', table_name='products')
    op.drop_index('idx_products_sku', table_name='products')
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_expenses_user_id', table_name='expenses')
    op.drop_index('idx_expenses_store_id', table_name='expenses')
    op.drop_index('idx_expenses_expense_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('warehouses')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_store_id', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_table('users')
    op.drop_table('product_categories')
    op.drop_table('tax_details')
    op.drop_table('stores')
    op.drop_table('roles')
    # ### end Alembic commands ###
